/*
 * Blood management API
 *
 * Management of blood donors and blood units
 *
 * API version: 1.0.0
 * Contact: xsykoram3@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package sprava_krvi

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type DonorsAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // CreateDonor - Creates new donor
   CreateDonor(ctx *gin.Context)

    // DeleteDonor - Deletes the specific donor
   DeleteDonor(ctx *gin.Context)

    // GetDonor - Provides the detail of a donor
   GetDonor(ctx *gin.Context)

    // GetDonors - Provides the list of blood donors
   GetDonors(ctx *gin.Context)

    // UpdateDonor - updates the data of the specified donor
   UpdateDonor(ctx *gin.Context)

 }

// partial implementation of DonorsAPI - all functions must be implemented in add on files
type implDonorsAPI struct {

}

func newDonorsAPI() DonorsAPI {
  return &implDonorsAPI{}
}

func (this *implDonorsAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodPost, "/donors", this.CreateDonor)
  routerGroup.Handle( http.MethodDelete, "/donors/:donorId", this.DeleteDonor)
  routerGroup.Handle( http.MethodGet, "/donors/:donorId", this.GetDonor)
  routerGroup.Handle( http.MethodGet, "/donors", this.GetDonors)
  routerGroup.Handle( http.MethodPut, "/donors/:donorId", this.UpdateDonor)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // CreateDonor - Creates new donor
// func (this *implDonorsAPI) CreateDonor(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // DeleteDonor - Deletes the specific donor
// func (this *implDonorsAPI) DeleteDonor(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetDonor - Provides the detail of a donor
// func (this *implDonorsAPI) GetDonor(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetDonors - Provides the list of blood donors
// func (this *implDonorsAPI) GetDonors(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // UpdateDonor - updates the data of the specified donor
// func (this *implDonorsAPI) UpdateDonor(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

