/*
 * Blood management API
 *
 * Management of blood donors and blood units
 *
 * API version: 1.0.0
 * Contact: xsykoram3@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package sprava_krvi

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type UnitsAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // CreateUnits - Creates new units
   CreateUnits(ctx *gin.Context)

    // DeleteUnit - Deletes the specific unit
   DeleteUnit(ctx *gin.Context)

    // GetUnit - Provides the detail of the unit
   GetUnit(ctx *gin.Context)

    // GetUnits - Provides the list of blood units
   GetUnits(ctx *gin.Context)

    // UpdateUnit - updates the data of the specified unit
   UpdateUnit(ctx *gin.Context)

 }

// partial implementation of UnitsAPI - all functions must be implemented in add on files
type implUnitsAPI struct {

}

func newUnitsAPI() UnitsAPI {
  return &implUnitsAPI{}
}

func (this *implUnitsAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodPost, "/units", this.CreateUnits)
  routerGroup.Handle( http.MethodDelete, "/units/:unitId", this.DeleteUnit)
  routerGroup.Handle( http.MethodGet, "/units/:unitId", this.GetUnit)
  routerGroup.Handle( http.MethodGet, "/units", this.GetUnits)
  routerGroup.Handle( http.MethodPut, "/units/:unitId", this.UpdateUnit)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // CreateUnits - Creates new units
// func (this *implUnitsAPI) CreateUnits(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // DeleteUnit - Deletes the specific unit
// func (this *implUnitsAPI) DeleteUnit(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetUnit - Provides the detail of the unit
// func (this *implUnitsAPI) GetUnit(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetUnits - Provides the list of blood units
// func (this *implUnitsAPI) GetUnits(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // UpdateUnit - updates the data of the specified unit
// func (this *implUnitsAPI) UpdateUnit(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

