/*
 * Blood management API
 *
 * Management of blood donors and blood units
 *
 * API version: 1.0.0
 * Contact: xsykoram3@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sprava_krvi

import (
	"time"
)

// Donor - Contains the data being stored, regaring a single blood donor
type Donor struct {

	Id string `json:"id,omitempty"`

	BirthNumber string `json:"birth_number"`

	FirstName string `json:"first_name"`

	LastName string `json:"last_name"`

	// for broad location
	PostalCode string `json:"postal_code"`

	BloodType string `json:"blood_type,omitempty"`

	BloodRh string `json:"blood_rh,omitempty"`

	Eligible bool `json:"eligible"`

	LastDonation time.Time `json:"last_donation,omitempty"`

	Email string `json:"email,omitempty"`

	PhoneNumber string `json:"phone_number,omitempty"`

	Diseases []string `json:"diseases,omitempty"`

	Medications []string `json:"medications,omitempty"`

	Substances []string `json:"substances,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
