/*
 * Blood management API
 *
 * Management of blood donors and blood units
 *
 * API version: 1.0.0
 * Contact: xsykoram3@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sprava_krvi

import (
	"time"
)

// Unit - Contains the data being stored, regaring a single blood unit
type Unit struct {

	Id string `json:"id,omitempty"`

	DonorId string `json:"donor_id"`

	BloodType string `json:"blood_type,omitempty"`

	BloodRh string `json:"blood_rh,omitempty"`

	Status string `json:"status,omitempty"`

	// for broad location
	Location string `json:"location"`

	Contents UnitContents `json:"contents,omitempty"`

	Frozen bool `json:"frozen,omitempty"`

	Diseases []string `json:"diseases,omitempty"`

	Expiration time.Time `json:"expiration,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
