/*
 * Blood management API
 *
 * Management of blood donors and blood units
 *
 * API version: 1.0.0
 * Contact: xsykoram3@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sprava_krvi

type UnitContents struct {

	Hemoglobin float32 `json:"hemoglobin,omitempty"`

	Erythrocytes bool `json:"erythrocytes,omitempty"`

	Leukocytes bool `json:"leukocytes,omitempty"`

	Platelets bool `json:"platelets,omitempty"`

	Plasma bool `json:"plasma,omitempty"`

	Additional []string `json:"additional,omitempty"`
}
