/*
 * Blood management API
 *
 * Management of blood donors and blood units
 *
 * API version: 1.0.0
 * Contact: xsykoram3@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sprava_krvi

// UnitListEntry - Contains simplified blood unit data
type UnitListEntry struct {

	Id string `json:"id"`

	BloodType string `json:"blood_type,omitempty"`

	BloodRh string `json:"blood_rh,omitempty"`

	Status string `json:"status"`

	// for broad location
	Location string `json:"location"`
}
