/*
 * Blood management API
 *
 * Management of blood donors and blood units
 *
 * API version: 1.0.0
 * Contact: xsykoram3@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sprava_krvi

import (
	"time"
)

// DonorListEntry - Contains simplified data, regaring a single blood donor
type DonorListEntry struct {

	Id string `json:"id"`

	FirstName string `json:"first_name"`

	LastName string `json:"last_name"`

	BloodType string `json:"blood_type,omitempty"`

	BloodRh string `json:"blood_rh,omitempty"`

	Eligible bool `json:"eligible"`

	LastDonation time.Time `json:"last_donation,omitempty"`
}
