/*
 * Blood management API
 *
 * Management of blood donors and blood units
 *
 * API version: 1.0.0
 * Contact: xsykoram3@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sprava_krvi

import (
    "github.com/gin-gonic/gin"
)

func AddRoutes(engine *gin.Engine) {
  group := engine.Group("/api")
  
  {
    api := newDonorsAPI()
    api.addRoutes(group)
  }
  
}
